# Generated by Django 2.2.4 on 2019-08-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_buku_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(blank=True, upload_to='buku/cover/'),
        ),
    ]
